source 'https://rubygems.org'

gem 'sinatra'
gem 'slim'
gem 'pg' # Postgres
gem 'bcrypt'
gem 'rerun'
gem 'awesome_print'
gem 'sassc'
gem 'sinatra-flash'
gem 'capybara'
gem 'rspec'
gem 'selenium-webdriver'
gem 'irb'
gem 'rack-ssl'
gem 'faker'
gem 'pony'
gem 'pandoc-ruby'
gem 'email_validator'
